-- Generated by AI
-- Create the Stocks table
CREATE TABLE Stocks (
    ticker VARCHAR(10) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    sector VARCHAR(100),
    exchange VARCHAR(50),
    country VARCHAR(50)
);

-- Create the StockPrices table
CREATE TABLE StockPrices (
    ticker VARCHAR(10) NOT NULL,
    price_date DATE NOT NULL,
    open NUMERIC(10, 2),
    high NUMERIC(10, 2),
    low NUMERIC(10, 2),
    close NUMERIC(10, 2),
    volume BIGINT,
    PRIMARY KEY (ticker, price_date),
    FOREIGN KEY (ticker) REFERENCES Stocks(ticker)
);

-- Optional: Create the CorporateActions table
CREATE TABLE CorporateActions (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    event_date DATE NOT NULL,
    event_type VARCHAR(50),
    value NUMERIC(10, 2),
    FOREIGN KEY (ticker) REFERENCES Stocks(ticker)
);
